#!/bin/bash

if [ ! -e cli ]; then
  echo "No cli directory."
  exit -1
fi

rm -fr core* vaultDisk fru.log

cd cli
files=`ls | grep -v "instance.properties\|connections\|nsfw\|VPlexcli-init\|shell-history\|VPlexconfig.xml\|chimera"`
echo $files
rm -fr $files

if [ -e chimera ]; then
  cd chimera
  files=`ls | grep -v "config"`
  rm -fr $files
fi

cd ../../
