#!/bin/bash

 if [ ! -e cli ]; then
    echo "No cli directory."
    exit -1
 fi

rm -fr core* vaultDisk fru.log

cd cli
files=`ls | grep -v "connections\|nsfw\|VPlexcli-init\|shell-history\|VPlexconfig.xml\|config"`
echo $files
rm -fr $files

cd ../
