#!/bin/bash

if [ $# -lt 1 ];then
  echo "Error: missing search string."
fi

files=""

for file in $@
do
  tmp=`find . -iname "$file"`

  if [ "$tmp" != "" ]; then
    files="$files $tmp"
  fi
done

if [ "$files" == "" ]; then
  exit
fi

gvim $files
