#!/bin/bash

if [ $# -lt 1 ];then
  echo "Error: missing search string."
fi

files=""

# input is a list of (possibly partial) filenames
for file in $@
do
  tmp=`find . -iname "$file"`

  if [ "$tmp" != "" ]; then
    files="$files $tmp"
  fi
done

# Found no matching files. Interpret input as a regex instead
if [ "$files" == "" ]; then
  echo "Interpreting input as regex..."
  files=`git grep -il "$@"`
fi

if [ "$files" == "" ]; then
  echo "No matching files found."
  exit 1
fi

gvim $files
