#!/bin/bash

git filter-branch -f --env-filter '
    if [[ "$GIT_AUTHOR_NAME" = "abertoldi" ]];
    then
        export GIT_AUTHOR_EMAIL="axel.von.bertoldi@kirasystems.com";
        export GIT_AUTHOR_NAME="Axel von Bertoldi";
    fi' \
`git upstream`..HEAD
