#!/bin/bash

git filter-branch -f --env-filter '
    if [[ "$GIT_AUTHOR_EMAIL" = "bertoldia@gmail.com" || "$GIT_COMMITTER_EMAIL" = "bertoldia@gmail.com" ]];
    then
        export GIT_COMMITTER_EMAIL="abertoldi@atb.com";
        export GIT_AUTHOR_EMAIL="abertoldi@atb.com";
    fi' \
`git upstream`..HEAD
