#!/bin/bash

BIN_PATH=$(dirname $(readlink -fn $0))
source $BIN_PATH/utils

MAKE_TARBALL=false
SP_SYNC=false
CLEAN=false
GIT_REPO_ROOT="/dev/null"


DO_CLEAN=false
DO_TESTS=false
DO_CLEAN_ONLY=false
TEST=""


usage() {
  echo "Usage: jmake [-t -u -s -c]"
  echo "  -t: make a release tarball"
  echo "  -u: execute unit tests"
  echo "  -s: sp-sync the resulting tarball. Implies -t."
  echo "  -c: clean before building."
  echo "  -cc: clean only. Ignores all other options."
  echo "  -6: use java 6."
  echo "  -2: use maven 2."
  exit 0
}

execAction() {
  echo -e "\e[1;33m  Executing $@ in `pwd` \e[0m"
  $@
}

#START
while getopts "ctush62" flag
do
  case $flag in
    s) SP_SYNC=true
       MAKE_TARBALL=true
      ;;
    t) MAKE_TARBALL=true;;
    u) DO_TESTS=true
       if [ $# -gt 1 ];then
         TEST=$2
       fi
       ;;
    c) if [[ $DO_CLEAN == true ]]; then
         DO_CLEAN_ONLY=true
       fi
       DO_CLEAN=true
       ;;
    6) export SMS_V2_JAVA_HOME=$JAVA6;;
    2) export SMS_V2_MAVEN_HOME=$MVN2;;
    h) usage;;
    *) usage;;
  esac
done

loadBuildEnvironment
setSmsv2Path

echo $PATH

ACTION="mvn"

if [[ $DO_CLEAN == true ]]; then
  ACTION="$ACTION clean"
fi

ACTION="$ACTION install"

if [[ $DO_TESTS == false ]]; then
  ACTION="$ACTION -e -Dmaven.test.skip"
elif [[ $TEST ]]; then
  ACTION="$ACTION -Dtest=$TEST"
fi

# Clobber all of the above and just clean
if [[ $DO_CLEAN_ONLY == true ]]; then
  ACTION="mvn clean"
  MAKE_TARBALL=false
  SP_SYNC=false
fi

rm $GIT_REPO_ROOT/$SMSV2_PATH/*.tgz

WD=`pwd`

# Build other sub-projects...
if [[ $DO_TESTS == false && $# -gt 1 ]];then
  cd $2
  execAction $ACTION
fi

if [ $? != 0  ]; then
  exit $?
fi

cd $WD

execAction $ACTION

if [[ $? == 0 && $MAKE_TARBALL == true ]]; then
  if [ basename != $SMSV2_PATH ]; then
    cd `git rev-parse --show-toplevel`
    cd $SMSV2_PATH
  fi

  if [ ! -e target/test-classes ]; then
    mkdir -p target/test-classes
  fi

  execAction "ant make-docless-tarball"
fi

if [ $? == 0 ]; then
  echo -e "\e[1;33m Last build at `date`\e[0m"
fi

  if [ $? == 0 -a $SP_SYNC == true ]; then
  sptool -c
  sptool -p smsv2-D*0*.tgz
fi

exit 0
