#!/bin/bash

BIN_PATH=$(dirname $(readlink -fn $0))
source $BIN_PATH/utils

ACTION="python2 make.py -j6"

usage() {
  echo "Usage: nmake [-c]"
  echo "  -c: make clean."
  exit 0
}

#START
isNsfwRepo

while getopts "c" flag
do
  case $flag in
    c) ACTION="python2 make.py clean";;
    *) usage;;
  esac
done

cd $GIT_REPO_ROOT/work
#find . -name '*.gcda' -exec rm {} \;
execAction $ACTION

exit $?
