#!/bin/bash

if [ $# -lt 1 ]
then
    n=1     # Just the latest picture
else
    n=$1    # The last j pictures
fi

echo "Adding the last $n pictures"

i=-1;
for file in /media/disk/DCIM/100_PANA/*.JPG
do
    i=$[$i+1]
    files[$i]=$file
done

length=${#files[@]}

j=0
while [ ${j} -lt $n ]
do
    echo "Adding ${files[$length-$j-1]}"
    cp ${files[$length-$j-1]} ~/Dropbox/Mom 
    j=$[$j+1]
done

#jhead -cmd "mogrify -resize 800x600 &i" *.JPG
jhead -autorot -nf%Y_%m_%d *.JPG
mogrify -resize 800x600 *.jpg
chmod 644 *.jpg
