#!/bin/bash

if [ $# -lt 1 ]
then
    tmp=`pwd`
    album=`basename "$tmp"`
else
    album=`basename "$1"`
    cd $1
fi


mkdir -p "/tmp/$album"
cp *.jpg "/tmp/$album"
cd "/tmp/$album"

mogrify -resize 1280x1024 *
#mogrify -resize 800x600 *;
#mogrify -resize 1600x1200 *;
cd ../
mv "$album" ~/Dropbox/Photos/
echo "Done."
