#!/bin/bash

################################################################################
usage() {
  echo "Usage: repos [any git command]"
    exit
}
################################################################################

if [ $# == 0 ]; then
        action="dirname {}"
    else
            action="cd {}/../; git $1"
        fi

        repos=$(find . -maxdepth 3 -type d -name .git)
        parallel $action ::: $repos 2> /dev/null
