#!/bin/bash

BUILD_ENVIRONMENT="build_environment"
SMSV2_PATH="com-yottayotta-smsv2"

isValidCLIRunDir() {
  if [ ! -e cli ]; then
     echo "Missing cli directory."
     exit -1
  fi

  if [[ ! -e VPlexcli-init && ! -e cli/VPlexcli-init ]]; then
     echo "Missing VPlexcli-init."
     exit -1
  fi

  if [ -e 'cli/.VPlexcli-lock' ]; then
    echo "A regression test is already running asshole."
    exit -1
  fi
}

loadBuildEnvironment() {
  if [ -z "$MAVEN_HOME" ]; then
    if [ -f $UI_DEV_DIR/$BUILD_ENVIRONMENT ]; then
      . $UI_DEV_DIR/$BUILD_ENVIRONMENT
      echo "Using JAVA_HOME=$JAVA_HOME"
    elif [ -f $UI_DEV_DIR/../$BUILD_ENVIRONMENT ]; then
      . $UI_DEV_DIR/../$BUILD_ENVIRONMENT
      echo "Using JAVA_HOME=$JAVA_HOME"
    else
      echo "Could not find $BUILD_ENVIRONMENT. Bailing!!!"
      exit 1
    fi
  fi
}

setSmsv2Path() {
    if [ -e $UI_DEV_DIR/'com-emc-vplex-smsv2' ]; then
      SMSV2_PATH="com-emc-vplex-smsv2"
    fi
}

if [ -z "$UI_DEV_DIR" ]; then
  echo "$UI_DEV_DIR not defined. Bailing."
  exit -1
fi

isValidCLIRunDir
loadBuildEnvironment
setSmsv2Path

TARBALL_PATH="${UI_DEV_DIR}/$SMSV2_PATH"
USE_NEW_RELEASE=true

while getopts "e" flag
do
  case $flag in
    e) USE_NEW_RELEASE=false;;
  esac
done

rm -fr 2siteSystem/capture

if [ $USE_NEW_RELEASE == true ]; then
  WD=$(pwd)

  cd ${TARBALL_PATH}
  TARBALL=$(ls *.tgz)
  end=${#TARBALL}-4
  CURRENT_SMS=${TARBALL:0:${end}}

  cd ${WD}

  rm -fr 2siteSystem
  cp -R ${TARBALL_PATH}/regression-tests/2siteSystem .
  find 2siteSystem -name '*.swp' -exec rm {} \;

  rm -fr ${CURRENT_SMS}
  tar -zxf ${TARBALL_PATH}/${CURRENT_SMS}.tgz

else
  CURRENT_SMS=$(ls -d smsv2-D*)
fi

cleanup

export EXTRA_JVM_OPTS="-DlinuxTowerSetupArgsFile=linuxTowerSetupArgs.py"

${CURRENT_SMS}/VPlexcli --cli-directory cli -s 51112

#zcli.sh
