#!/bin/bash

BIN_PATH=$(dirname $(readlink -fn $0))
source $BIN_PATH/utils
source $HOME/.build_environment

USE_NEW_TARBALL=true
DEBUG=false
BASE_SPAWN_CMD="VPlexcli --cli-directory cli -s 51111"
DEBUG_SPAWN_CMD="jdb.sh --dbgport=4000"

usage() {
  echo "Run the last compiled cli"
  echo "Usage: run-cli [-e -d -8]"
  echo "  -d: with debug."
  echo "  -e: use the already unpacked cli tarball."
  echo "  -8: use java 8."
  exit 0
}

while getopts "ed8" flag
do
  case $flag in
    e) USE_NEW_TARBALL=false;;
    d) DEBUG=true;;
    8) export SMS_V2_JAVA_HOME=$JAVA8;;
    h) usage;;
    *) usage;;
  esac
done

isValidCLIRunDir
loadBuildEnvironment $UI_DEV_DIR
setSmsv2Path $UI_DEV_DIR

echo $PATH

if [ $USE_NEW_TARBALL == true ]; then
  WD=${PWD}
  cd ${UI_DEV_DIR}/$SMSV2_PATH
  TARBALL=`ls *.tgz`
  end=${#TARBALL}-4
  CURRENT_SMS=${TARBALL:0:${end}}

  cd ${WD}
  rm -fr ${CURRENT_SMS}
  tar -zxf ${UI_DEV_DIR}/$SMSV2_PATH/${TARBALL}
else
  if [ $(ls | grep smsv2-D | wc -l) -gt 1 ]; then
    echo "Which one?"
    ls -hl smsv2-D*
    exit 1
  fi

  CURRENT_SMS=`ls | grep smsv2-`
fi

if [ $DEBUG  == true ]; then
  echo "Spawning in debug mode"
  SPAWN_CMD="${CURRENT_SMS}/${DEBUG_SPAWN_CMD} ${CURRENT_SMS}/${BASE_SPAWN_CMD}"
else
  SPAWN_CMD="${CURRENT_SMS}/${BASE_SPAWN_CMD}"
fi

cleanup
echo ${SPAWN_CMD}
${SPAWN_CMD}
