#!/bin/bash

BIN_PATH=$(dirname $(readlink -fn $0))
source $BIN_PATH/utils

isValidCLIRunDir
loadBuildEnvironment $UI_DEV_DIR
setSmsv2Path $UI_DEV_DIR

USE_NEW_TARBALL=true
DEBUG=false
BASE_SPAWN_CMD="VPlexcli --cli-directory cli -s 51111"
DEBUG_SPAWN_CMD="jdb.sh --dbgport=4000"

while getopts "ed" flag
do
  case $flag in
    e) USE_NEW_TARBALL=false;;
    d) DEBUG=true;;
  esac
done

if [ $USE_NEW_TARBALL == true ]; then
  WD=${PWD}
  cd ${UI_DEV_DIR}/$SMSV2_PATH
  TARBALL=`ls *.tgz`
  end=${#TARBALL}-4
  CURRENT_SMS=${TARBALL:0:${end}}

  cd ${WD}
  rm -fr ${CURRENT_SMS}
  tar -zxf ${UI_DEV_DIR}/$SMSV2_PATH/${TARBALL}
else
  if [ $(ls | grep smsv2-D | wc -l) -gt 1 ]; then
    echo "Which one?"
    ls -hl smsv2-D*
    exit 1
  fi

  CURRENT_SMS=`ls | grep smsv2-`
fi

if [ $DEBUG  == true ]; then
  SPAWN_CMD="${CURRENT_SMS}/${DEBUG_SPAWN_CMD} ${CURRENT_SMS}/${BASE_SPAWN_CMD}"
else
  SPAWN_CMD="${CURRENT_SMS}/${BASE_SPAWN_CMD}"
fi

cleanup
${SPAWN_CMD}