#!/bin/bash

BIN_PATH=$(dirname $(readlink -fn $0))
source $BIN_PATH/utils

TARBALL_PATH="${UI_DEV_DIR}/$SMSV2_PATH"
USE_NEW_RELEASE=true

usage() {
  echo "Run the last compiled cli"
  echo "Usage: run-regression-test [-e -8]"
  echo "  -e: use the already unpacked cli tarball."
  echo "  -8: use java 8."
  exit 0
}

while getopts "e8" flag
do
  case $flag in
    e) USE_NEW_RELEASE=false;;
    8) export SMS_V2_JAVA_HOME=$JAVA8;;
    h) usage;;
    *) usage;;
  esac
done

isValidCLIRunDir
loadBuildEnvironment $UI_DEV_DIR
setSmsv2Path $UI_DEV_DIR

rm -fr 2siteSystem/capture

if [ $USE_NEW_RELEASE == true ]; then
  WD=$(pwd)

  cd ${TARBALL_PATH}
  TARBALL=$(ls *.tgz)
  end=${#TARBALL}-4
  CURRENT_SMS=${TARBALL:0:${end}}

  cd ${WD}

  rm -fr 2siteSystem
  cp -R ${TARBALL_PATH}/regression-tests/2siteSystem .
  find 2siteSystem -name '*.swp' -exec rm {} \;

  rm -fr ${CURRENT_SMS}
  tar -zxf ${TARBALL_PATH}/${CURRENT_SMS}.tgz

else
  CURRENT_SMS=$(ls -d smsv2-D*)
fi

cleanup

export EXTRA_JVM_OPTS="-DlinuxTowerSetupArgsFile=linuxTowerSetupArgs.py \
                       -Dtesttools.dir=../../chimera
                       -Dtesttools.config=../SysConfigFile.xml"

${CURRENT_SMS}/VPlexcli --cli-directory cli -s 51112

#zcli.sh
