#!/bin/bash

BIN_PATH=$(dirname $(readlink -fn $0))
source $BIN_PATH/utils

export DIST_PYTHON="/usr/bin/python2"

RUNNER_HOME="/home/runner"
CTEST_BIN="${RUNNER_HOME}/bin/ctest"
LOCAL_RUNNER="/home/bertoa/runner"

usage() {
  echo "Usage: runner-bin <system> [-s|-h|-n[-b, -e, -t]]"
  echo "  -s: show (default)."
  echo "  -n: submit new job."
  echo "  -b: The branch to submit (defaults to the currently checked out branch)."
  echo "  -t: test only. Don't actually submit new job request."
  echo "  -h: help."
  exit
}

if [ $# == 0 ]; then
  echo "Error: missing system."
  usage
fi

setSmsv2Path

SYSTEM=$1
shift

ACTION="show"
BRANCH=`git current-branch`
TEST=false

while getopts "b:snth" flag
do
  case $flag in
    b) BRANCH=$OPTARG;;
    s) ACTION="show";;
    n) ACTION="submit";;
    t) TEST=true;;
    h) usage;;
  esac
done

case $ACTION in
  show)
    ${CTEST_BIN} ${SYSTEM} show
    exit
    ;;
  submit)
    COMMAND="${CTEST_BIN} ${SYSTEM} submitsms ${BRANCH}"
    echo ${COMMAND}

    if [ $TEST == false ]; then
      exec ${COMMAND}
    fi
    ;;
esac
