#!/bin/bash

regen_ctags=false
regen_eclipse=false
do_clean=false

usage() {
  echo "Tidy your git repo:"
  echo "Usage: tidy [-c -a]"
  echo "  -a: have ant regenerate eclipse project files."
  echo "  -t: regenerate your ctags."
  echo "  -c: git clean the repo."
  exit 0
}

while getopts "thac" flag
do
  case $flag in
    t) regen_ctags=true;;
    a) regen_eclipse=true;;
    c) do_clean=true;;
    h) usage;;
    *) usage;;
  esac
done

cd `git rev-parse --show-toplevel`
git fetch
git remote prune origin
git prune
git gc
git fsck

if [[ $do_clean == true ]]; then
  git clean -fx -e .metadata -e tags -e .project -e .classpath
fi

if [[ $regen_eclipse == true ]]; then
  . build_environment
  ant
fi

if [[ $regen_ctags == true ]]; then
  ctags -R --fields=+l --extra=+q . >/dev/null 2>&1 &
fi

