#!/bin/bash

GIT_REPO_ROOT="/dev/null"

setGitRepoRoot() {
  GIT_REPO_ROOT=`git rev-parse --show-toplevel`
  if [ $? != 0  ]; then
    echo "Error: not a git repository!"
    exit $?
  fi
}

findFirstBuildDir() {
  setGitRepoRoot
  if [ $# -gt 0 ]; then
    cd $1
  fi
  while [ ! -e pom.xml ]; do
    cd ../
  done
}

function die {
    echo $*
    exit 1
}

execAction() {
  echo -e "\e[1;33mExecuting $@ in `pwd` \e[0m"
  $@ || die $@ $?
}
