#!/bin/bash

SPGEAR="/spgear/zeph_comp_tools"
JAVA8="$SPGEAR/jdk1.8.0_05"
JAVA6="$SPGEAR/jdk1.6.0_45"
MVN2="$SPGEAR/apache-maven-2.2.1"
MVN3="$SPGEAR/apache-maven-3.2.2"
GIT_REPO_ROOT="/dev/null"

setGitRepoRoot() {
  GIT_REPO_ROOT=`git rev-parse --show-toplevel`
  if [ $? != 0  ]; then
    echo "Error: not a git repository!"
    exit $?
  fi
}

SMSV2_PATH="com-yottayotta-smsv2"

setSmsv2Path() {
  if [ $# == 0 ]; then
    setGitRepoRoot
    SEARCH=$GIT_REPO_ROOT
  else
    SEARCH=$1
  fi

  if [ -e $SEARCH/'com-emc-vplex-smsv2' ]; then
    SMSV2_PATH="com-emc-vplex-smsv2"
  fi
}

BUILD_ENVIRONMENT="build_environment"

loadBuildEnvironment() {
  if [ $# == 0 ]; then
    setGitRepoRoot
    SEARCH=$GIT_REPO_ROOT
  else
    SEARCH=$1
  fi

  if [ -z $MAVEN_HOME ]; then
    if [ -f $SEARCH/$BUILD_ENVIRONMENT ]; then
      source $SEARCH/$BUILD_ENVIRONMENT
    elif [ -f $SEARCH/../$BUILD_ENVIRONMENT ]; then
      source $SEARCH/../$BUILD_ENVIRONMENT
    else
      echo "Could not find $BUILD_ENVIRONMENT. Bailing!!!"
      exit 1
    fi
  fi
}

isValidCLIRunDir() {
  if [ ! -e cli ]; then
    echo "Missing cli directory."
    exit -1
  fi

  if [[ ! -e cli/VPlexcli-init && ! -e VPlexcli-init ]]; then
    echo "Missing VPlexcli-init."
    exit -1
  fi

  if [ -e 'cli/.VPlexcli-lock' ]; then
    echo "A cli is already running asshole."
    exit -1
  fi
}

findFirstBuildDir() {
  setGitRepoRoot
  if [ $# -gt 0 ]; then
    cd $1
  fi
  while [ ! -e pom.xml ]; do
    cd ../
  done
}

isNsfwRepo() {
  setGitRepoRoot

  if [[ ! -e $GIT_REPO_ROOT/snac ]]; then
    echo "Error: not an nsfw repository!"
    exit 1
  fi
}

function die {
    echo $*
    exit 1
}

execAction() {
  echo -e "\e[1;33mExecuting $@ in `pwd` \e[0m"
  $@ || die $@ $?
}
