#!/bin/bash

address=`ifconfig enp0s25 | grep 'inet ' | awk '{print $2}' | sed 's/addr://'`

cd ~/.bin
echo "#!/bin/bash" > bertoa
echo "" >> bertoa
echo "ssh -X bertoa@$address" >> bertoa
chmod +x bertoa
echo ${address}
