#!/bin/bash

RSYNC_CMD='rsync'
RSYNC_ARGS='-avz --exclude .git -e ssh'
REMOTE_HOST='bertoa@bertoa:'
REMOTE_HOME='/local/home/bertoa'
LOCAL_HOME='/home/axel'
ACTION=''

while getopts "ls" flag
do
    case $flag in
        s) ACTION='push' ;;
        l) ACTION='pull' ;;
        *) exit -1 ;;
    esac
done

if [ ! -e $2 ]; then
  mkdir -p $2
fi

LOCAL_PATH_TO_SYNC=$(readlink -f $2)
PATH_TO_SYNC_NO_HOME=${LOCAL_PATH_TO_SYNC#$LOCAL_HOME}
REMOTE_PATH_TO_SYNC=$REMOTE_HOME$PATH_TO_SYNC_NO_HOME

if [[ $ACTION == 'pull' ]];
then
    CMD="$RSYNC_CMD $RSYNC_ARGS $REMOTE_HOST$REMOTE_PATH_TO_SYNC/ $LOCAL_PATH_TO_SYNC/"
elif [[ $ACTION == 'push' ]];
then
    CMD="$RSYNC_CMD $RSYNC_ARGS $LOCAL_PATH_TO_SYNC/ $REMOTE_HOST$REMOTE_PATH_TO_SYNC/"
fi

echo $CMD
exec $CMD
